 id | map_id |              title               | date_created |          description           |                                                                                                                                                                           image                                                                                                                                                                           |    lat    |         lng         
----+--------+----------------------------------+--------------+--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------------------
  1 |      1 | Stanley Park                     | 2019-03-26   | The greatest park in the world | I AM AN IMAGE                                                                                                                                                                                                                                                                                                                                             |           | 
  2 |      2 | Cafe                             | 2019-03-27   | Where coffee zombies live      | I AM AN IMAGE                                                                                                                                                                                                                                                                                                                                             |           | 
  3 |        | Lighthouse Park | West Vancouver | 2019-03-30   | test entry                     |                                                                                                                                                                                                                                                                                                                                                           |           | 
  4 |        | Lighthouse Labs                  | 2019-03-30   | bootcamp!                      | https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAuwJSC2vQ5tsF6jL9AdkQrXpzjD_AObqMytur3s9JlO3qWcxHfuPeYMLtQX_f32feaHe8BcfnbVAQdthgbqMeb4FohTLSQKpfRjTgeIaIljIbrRTAt0ua9i7cQ8LJto7CEhBxsxnXw5pJFPpOwm3fThHHGhSRFHMXxg4UCePn5KnRPRXS9eOoWw&3u2048&5m1&2e1&callback=none&key=AIzaSyA7JuJpmxAYqCHC0Z_7STfFWPpXGZ-Z_aU&token=64181 | 49.2812   | -123.11484300000001
  5 |        | Downtown Vancouver               | 2019-03-30   | Smells like pee                | https://maps.googleapis.com/maps/api/place/js/PhotoService.GetPhoto?1sCmRaAAAAaMAxNnMqhKgJChKfQqP8tHcO-eyKqMte-2uTdCF8KISAO_i1ElEyQ7VohJm5c799JwDI2FDTohQxiT6vizZXGX0hKw7-pg5hWS0dnfiqpFUtct1AkEi95R_FPGPOVQQ9EhDo6PCDbJg2kyGGTlPrgVaVGhRS6Y6eqynsazllWMT8XKD8Ryy9vA&3u4416&5m1&2e1&callback=none&key=AIzaSyA7JuJpmxAYqCHC0Z_7STfFWPpXGZ-Z_aU&token=4575  | 49.281954 | -123.11707439999998
(5 rows)

